apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-${namespace}
  namespace: ${namespace}
spec:
  rules:
    - host: ${host_name}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${service_name}
                port:
                  number: ${port_number}
  ingressClassName: nginx
