apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: ${app_name}
  namespace: ${namespace}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "${environment}-${app_name}"
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_USER
            objectAlias: POSTGRES_USER
          - path: POSTGRES_PASSWORD
            objectAlias: POSTGRES_PASSWORD
          - path: GITHUB_TOKEN
            objectAlias: GITHUB_TOKEN
          - path: GITHUB_CLIENT_ID
            objectAlias: GITHUB_CLIENT_ID
          - path: GITHUB_CLIENT_SECRET
            objectAlias: GITHUB_CLIENT_SECRET
  secretObjects:
    - secretName: ${environment}-${app_name}
      type: Opaque
      data:
        - objectName: POSTGRES_USER
          key: POSTGRES_USER
        - objectName: POSTGRES_PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: GITHUB_TOKEN
          key: GITHUB_TOKEN
        - objectName: GITHUB_CLIENT_ID
          key: GITHUB_CLIENT_ID
        - objectName: GITHUB_CLIENT_SECRET
          key: GITHUB_CLIENT_SECRET
